name: 'dotnet build'

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [ closed ]

jobs:
  dotnet:
    uses: RaaLabs/reusable-workflows/.github/workflows/dotnet-build.yml@dmain
    with:
      IMAGE_NAME: 'connectors-opcua'
    secrets:
      DOCKER_REGISTRY_LOGIN_SERVER: ${{ secrets.RAAEDGE_LOGIN_SERVER }}
      DOCKER_REGISTRY_USERNAME: ${{ secrets.RAAEDGE_ACR_USERNAME }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.RAAEDGE_ACR_PASSWORD }}
      NUGET_GITHUB_PACKAGES_TOKEN: ${{ secrets.NUGET_GITHUB_PACKAGES_TOKEN }}
      NUGET_GITHUB_PACKAGES_USERNAME: ${{ secrets.NUGET_GITHUB_PACKAGES_USERNAME }}
