name: Sonarcloud

on:
  push:
    branches:
      - '**'

jobs:
  sonarcloud:
    uses: RaaLabs/reusable-workflows/.github/workflows/dotnet-sonarcloud.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      NUGET_GITHUB_PACKAGES_TOKEN: ${{ secrets.NUGET_GITHUB_PACKAGES_TOKEN }}
      NUGET_GITHUB_PACKAGES_USERNAME: ${{ secrets.NUGET_GITHUB_PACKAGES_USERNAME }}
